export const products = [
    {
      id: 1,
      title: "Ankle Socks",
      price: 120.0,
      oreginalPrice:"130",
      status: "New",
      sale: true,
      image: "/save image/1-cover (1).png",
    },
    {
      id: 2,
      title: "Air T-Shirt",
      price: 150.0,
      oreginalPrice:"160",
      status: "New",
      sale: true,
      image: "/save image/1-cover (2).png",
    },
    {
      id: 3,
      title: "Athletic Socks",
      price: 130.0,
      oreginalPrice:"140",
      status: "New",
      sale: true,
      image: "/save image/1-cover (3).png",
    },
    {
      id: 4,
      title: "Classic Shorts",
      price: 150.0,
      oreginalPrice:"160",
      status: "New",
      sale: true,
      image: "/save image/1-cover (4).png",
    },
    {
      id: 5,
      title: "Brown Jacket",
      price: 180.0,
      oreginalPrice:"190",
      status: "New",
      sale: true,
      image: "/save image/1-cover (5).png",
    },
    {
      id: 6,
      title: "Classic Green Pants",
      price: 140.0,
      oreginalPrice:"150",
      status: "New",
      sale: true,
      image: "/save image/1-cover (6).png",
    },
    {
      id: 7,
      title: "Classic Casual Wear",
      price: 160.0,
      oreginalPrice:"170",
      status: "New",
      sale: true,
      image: "/save image/1-cover (7).png",
    },
    {
      id: 8,
      title: "Classic Black Jeans",
      price: 150.0,
      oreginalPrice:"160",
      status: "New",
      sale: true,
      image: "/save image/1-cover (8).png",
    },
    {
      id: 9,
      title: "Classic Long Shirt",
      price: 190.0,
      oreginalPrice:"200",
      status: "New",
      sale: true,
      image: "/save image/1-cover (9).png",
    },
    {
      id: 10,
      title: "Classic Summer Dress",
      price: 170.0,
      oreginalPrice:"180",
      status: "New",
      sale: true,
      image: "/save image/1-cover (10).png",
    },
    {
      id: 11,
      title: "Classic Sweater",
      price: 180.0,
      oreginalPrice:"190",
      status: "New",
      sale: true,
      image: "/save image/1-cover (11).png",
    },
    {
      id: 12,
      title: "Classic White Sneaker",
      price: 120.0,
      oreginalPrice:"130",
      status: "New",
      sale: true,
      image: "/save image/1-cover (12).png",
    },
    {
      id: 13,
      title: "Softshell Joggers",
      price: 150.0,
      oreginalPrice:"160",
      status: "New",
      sale: true,
      image: "/save image/1-cover (13).png",
    },
    {
      id: 14,
      title: "Classic Denim Jacket",
      price: 120.0,
      oreginalPrice:"130",
      status: "New",
      sale: true,
      image: "/save image/1-cover (14).png",
    },
    {
      id: 15,
      title: "Basic Crop Top",
      price: 160.0,
      oreginalPrice:"170",
      status: "New",
      sale: true,
      image: "/save image/1-cover (15).png",
    },
    {
      id: 16,
      title: "Cut Fit Shorts",
      price: 180.0,
      oreginalPrice:"190",
      status: "New",
      sale: true,
      image: "/save image/1-cover (16).png",
    },
    {
      id: 17,
      title: "Classic T-Shirt",
      price: 120.0,
      oreginalPrice:"130",
      status: "New",
      sale: true,
      image: "/save image/1-cover (17).png",
    },
    {
      id: 18,
      title: "Ear-to-Shoulder Sweater",
      price: 155.0,
      oreginalPrice:"160",
      status: "New",
      sale: true,
      image: "/save image/1-cover (18).png",
    },
    {
      id: 19,
      title: "Essential Throw Blanket",
      price: 140.0,
      oreginalPrice:"160",
      status: "New",
      sale: true,
      image: "/save image/1-cover (19).png",
    },
    {
      id: 20,
      title: "Everyday Flex Socks",
      price: 140.0,
      oreginalPrice:"150",
      status: "New",
      sale: true,
      image: "/save image/1-cover (20).png",
    },
    {
      id: 21,
      title: "Daily Comfort Socks",
      price: 140.0,
      oreginalPrice:"150",
      status: "New",
      sale: true,
      image: "/save image/1-cover (1).png",
    },
    {
      id: 22,
      title: "Essential Gym Bag",
      price: 130.0,
      oreginalPrice:"150",
      status: "New",
      sale: true,
      image: "/save image/1-cover (1).png",
    },
    {
      id: 23,
      title: "Classic Sports Shoes",
      price: 160.0,
      oreginalPrice:"170",
      status: "New",
      sale: true,
      image: "/save image/1-cover (1).png",
    },
    {
      id: 24,
      title: "Classic Activewear Set",
      price: 170.0,
      oreginalPrice:"180",
      status: "New",
      sale: true,
      image: "/save image/1-cover (1).png",
    },
  ];